"""The working set (``working_set.yaml``) — which tools ride every turn.

Visibility, never authority. A name here has its schema in the per-turn payload;
a name absent from it is reached through ``tool_search`` at the cost of one
round trip. What any tool may DO is ``permissions.yaml`` and is a separate
question with a separate answer.

**No source-side copy of the roster.** There is deliberately nothing in code
to fall back to: a second copy is exactly the drift this file exists to end,
and a documented set the runtime never read is the defect that opened the
phase. The one source-side floor is ``FLOOR`` below, a single name.

This file names the SHIPPED half. Tools the operator wrote carry their own
promotions in ``home/tools/promoted.txt`` (``kernel/home_tools.py``), because
this one is regenerated by ``generate_working_set`` and ships, so a
machine-local name here would be destroyed by the next run or handed to
strangers. ``brain/boot.py::_apply_tool_tiers`` unions the two and is the only
place that knows the effective set.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml

from tesseract.paths import config_dir

logger = logging.getLogger(__name__)

CONFIG_FILENAME = "working_set.yaml"
CORE_KEY = "core"

#: Restored when the config omits it. It is the door to every tool not on the
#: list, so an assistant without it can reach only what that file happens to
#: name — which turns a spending dial into a capability cut, silently.
FLOOR: frozenset[str] = frozenset({"tool_search"})

#: Names no proposal may take off the list, wherever the proposal comes from.
#: `FLOOR` plus the playbook door. They are not the same set and must not be
#: merged: `FLOOR` is what `load_core_tool_names` RESTORES when the file omits
#: it, and restoring `playbook_search` on a machine with no playbooks would
#: put back a tool nothing needs. This is the narrower claim, that neither may
#: be REMOVED by something the operator did not type.
#:
#: One constant because there were two. `working_set_review` locked the pair
#: and `routes/workspace.py::_commit_working_set_proposal` locked only
#: `FLOOR`, so a card naming `playbook_search` for dropping would have been
#: applied at the one layer that is supposed to re-derive its guards
#: independently of the stage that filed the card.
UNDROPPABLE: frozenset[str] = FLOOR | frozenset({"playbook_search"})


def config_path() -> Path:
    """Call-time so a `TESSERACT_HOME` change after import is honored."""
    return config_dir() / CONFIG_FILENAME


def load_core_tool_names() -> frozenset[str]:
    """The configured working set, with `FLOOR` unioned in.

    Raises on a missing or malformed file — config seeding puts it there at
    every entry point, so its absence is a broken install rather than an
    operator choice, and guessing a roster would hide that. What it does NOT
    raise on is a set the operator has cut down, including to nothing: that is
    the dial being turned, and the floor is what keeps it from bricking.

    Names are not checked against the registry here. That happens in
    `brain/boot.py::_apply_tool_tiers`, which is the first point where a
    registry exists to check against.
    """
    path = config_path()
    if not path.is_file():
        raise FileNotFoundError(f"working set config missing: {path}")
    raw: Any = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"{path} must contain a mapping")
    if CORE_KEY not in raw:
        raise KeyError(f"{path} missing required key: {CORE_KEY!r}")
    entries = raw[CORE_KEY]
    if entries is None:
        entries = []
    if not isinstance(entries, list):
        raise ValueError(f"{path}::{CORE_KEY} must be a list of tool names")
    names = set()
    for i, entry in enumerate(entries):
        if not isinstance(entry, str) or not entry.strip():
            raise ValueError(
                f"{path}::{CORE_KEY}[{i}] must be a tool name, got {entry!r}"
            )
        names.add(entry.strip())

    restored = FLOOR - names
    if restored:
        logger.warning(
            "%s::%s does not list %s. Added back: without it the assistant can "
            "only reach the tools named in that file, and nothing on any screen "
            "would say so.",
            path, CORE_KEY, ", ".join(sorted(restored)),
        )
    return frozenset(names | FLOOR)
