"""Generate the sanitized production tree users download.

Reads the dev repo, writes a clean tree: only git-TRACKED files, config
shipped from hand-authored templates via make_shipping_config (Task 8b),
state dirs created empty, a small belt-and-braces glob denylist per
_production_manifest. NEVER writes into the source tree.
"""

from __future__ import annotations

import argparse
import fnmatch
import os
import shutil
import stat
import subprocess
from collections.abc import Iterable
from pathlib import Path

from ruamel.yaml import YAML

from tesseract.scripts import audit_release_tree
from tesseract.scripts._production_manifest import (
    EMPTY_DIRS,
    EXCLUDE_GLOBS,
    EXCLUDE_PATH_GLOBS,
    EXCLUDE_PATHS,
)
from tesseract.scripts.make_shipping_config import build_shipping_config
from tesseract.scripts.make_shipping_workspace import build_shipping_workspace


def _force_remove(func, path, _exc) -> None:
    """`shutil.rmtree` onexc hook: `copy2` preserves the source read-only bit
    (real files under e.g. `vault/raw/**`), which blocks deletion on Windows.
    """
    os.chmod(path, stat.S_IWRITE)
    func(path)


def tracked_files(src_root: Path) -> list[str]:
    """Repo-root-relative posix paths of every git-TRACKED file.

    Tracking status is the authority on what may ship: anything untracked or
    gitignored is machine-local or operator-private by construction.
    """
    out = subprocess.run(
        ["git", "-C", str(src_root), "ls-files", "-z"],
        capture_output=True,
        check=True,
    )
    return [p for p in out.stdout.decode("utf-8").split("\0") if p]


def _shippable(rel: str) -> bool:
    if any(rel == p or rel.startswith(f"{p}/") for p in EXCLUDE_PATHS):
        return False
    if any(fnmatch.fnmatch(rel, pat) for pat in EXCLUDE_PATH_GLOBS):
        return False
    name = rel.rsplit("/", 1)[-1]
    return not any(fnmatch.fnmatch(name, pat) for pat in EXCLUDE_GLOBS)


def _write_root_gitignore(out_root: Path) -> None:
    """Replace the dev repo's root `.gitignore` with one written for production.

    Dev's rules are safe in dev only because the files they name are ALREADY
    TRACKED there — git ignores untracked files, so a tracked file survives a
    matching rule. The production repo is initialised fresh, where nothing is
    tracked yet, so those same rules delete real content at `git add` time.

    That is not hypothetical: a bare `downloads/` rule (meant for the repo-root
    scratch dir) matches at ANY depth, so it silently dropped the
    `tesseract/mirror/server/downloads/` PACKAGE. Production shipped without it
    and every backend died with
    `ModuleNotFoundError: tesseract.mirror.server.downloads`. Six state dirs
    went the same way, 14 files in total.

    Production's own needs are small: a user's clone accumulates nothing, since
    all runtime state resolves OUTSIDE the code tree under `TESSERACT_HOME`.
    Only build/tool droppings need ignoring, and each shipped state dir carries
    its own scoped `.gitignore` (see `_write_state_dir_gitignore`).
    """
    (out_root / ".gitignore").write_text(
        "\n".join(
            (
                "# Production tree — generated by build_production_tree.py.",
                "# Deliberately minimal: it must never exclude shipped content.",
                "# Runtime state lives outside this tree, under TESSERACT_HOME.",
                "__pycache__/",
                "*.py[cod]",
                "*.egg-info/",
                ".pytest_cache/",
                "node_modules/",
                "target/",
                "dist/",
                ".venv/",
                "venv/",
                "",
            )
        ),
        encoding="utf-8",
    )


def _write_state_dir_gitignore(d: Path) -> None:
    """Ignore everything in a shipped state dir except its own scaffold files
    (plus this `.gitignore` itself). Belt-and-braces: if a fresh install's
    `TESSERACT_HOME` ever ends up inside a git repo of its own (or someone
    runs `git init` in it directly), operator content written into these
    dirs afterward can never be accidentally committed — only the shipped
    scaffold/product files are ever exceptions.
    """
    names = sorted(p.name for p in d.iterdir() if p.is_file() and p.name != ".gitignore")
    lines = ["*", "!.gitignore", *(f"!{name}" for name in names)]
    (d / ".gitignore").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _reset_entities(out_root: Path) -> None:
    """Blank `people` in the shipped `memory/entities.yaml`, if present.

    `people` holds only the operator's own entry; `projects`/`tools`/
    `concepts` are generic TESSERACT taxonomy and ship as-is. Only ever
    touches the OUTPUT copy — this runs after files are already copied.
    """
    entities_path = out_root / "tesseract" / "memory" / "entities.yaml"
    if not entities_path.is_file():
        return
    yaml = YAML()
    data = yaml.load(entities_path.read_text(encoding="utf-8"))
    if isinstance(data, dict) and "people" in data:
        data["people"] = []
    with entities_path.open("w", encoding="utf-8") as f:
        yaml.dump(data, f)


def build(src_root: Path, out_root: Path, files: Iterable[str] | None = None) -> None:
    """Copy the shippable tracked files of `src_root` into a fresh `out_root`.

    `files` (repo-root-relative posix paths) defaults to `tracked_files`;
    tests inject an explicit list so they need no git repo.
    """
    src_root, out_root = Path(src_root), Path(out_root)
    if src_root.resolve() == out_root.resolve():
        raise ValueError(f"out_root must differ from src_root ({src_root})")
    if out_root.resolve().is_relative_to(src_root.resolve()):
        raise ValueError("out_root must not live inside src_root")
    if src_root.resolve().is_relative_to(out_root.resolve()):
        # Reverse of the check above: if out_root is an ANCESTOR of src_root,
        # the rmtree below would delete the source tree. Reachable by swapping
        # the two CLI args, so guard it before any destructive write.
        raise ValueError("src_root must not live inside out_root")
    if out_root.exists():
        shutil.rmtree(out_root, onexc=_force_remove)
    out_root.mkdir(parents=True)

    for rel in tracked_files(src_root) if files is None else files:
        if not _shippable(rel):
            continue
        source = src_root / rel
        if source.is_symlink():
            # git tracks the path string, not the bytes: `is_file()`/`copy2`
            # resolve through a symlink, so a tracked link pointing outside the
            # repo would copy its target's LIVE content and defeat the
            # tracked-only allowlist. Skip links entirely (check the link, not
            # its target).
            continue
        if not source.is_file():
            continue
        target = out_root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)

    # Config: overwrite the copied tree with reset versions. REQUIRED — a
    # missing source dir must hard-fail (CL-m5), not silently ship an empty
    # tesseract/config/ (build_shipping_config's own glob over a nonexistent
    # src_dir finds nothing and returns quietly, so the guard must live here).
    src_config = src_root / "tesseract" / "config"
    if not src_config.is_dir():
        raise RuntimeError(
            f"build: missing required config source dir ({src_config}) — "
            "needed to build the shipped tesseract/config/ tree"
        )
    build_shipping_config(src_config, out_root / "tesseract" / "config")

    # Workspace: seed a neutral starter tree from hand-authored templates —
    # the operator's live tesseract/workspace/ never ships (Task 11f).
    # REQUIRED — build_shipping_workspace itself raises RuntimeError when
    # `_shipping` is missing or empty, naming the path; no outer guard needed.
    src_shipping_workspace = src_root / "tesseract" / "workspace" / "_shipping"
    out_workspace = out_root / "tesseract" / "workspace"
    build_shipping_workspace(src_shipping_workspace, out_workspace)
    # MUST accompany the copy, exactly as for the three state dirs below.
    # Without it the dev root `.gitignore`'s `tesseract/workspace/*` rule wins
    # over the freshly written scaffold and `git add` silently drops every file
    # — so `git push` shipped a production tree with no `tesseract/workspace/`
    # at all, and every install died at boot in `ensure_workspace_seeded()`.
    # Shipped as v1.0.0/v1.0.1 before anyone noticed; see the 2026-07-29
    # session note.
    _write_state_dir_gitignore(out_workspace)

    # Memory store / vault / tars-workshop: same templating shape as
    # workspace above — ship ready with hand-authored scaffold content
    # instead of an empty directory (Task 17). REQUIRED, same reasoning as
    # workspace above — build_shipping_workspace raises per-`rel` if absent.
    for rel in ("tesseract/memory-store", "tesseract/vault", "tesseract/tars-workshop"):
        src_shipping = src_root / rel / "_shipping"
        out_dir = out_root / rel
        build_shipping_workspace(src_shipping, out_dir)
        _write_state_dir_gitignore(out_dir)

    _reset_entities(out_root)

    # Voice model dirs: `fetch_piper_voice` downloads .onnx weights INTO the
    # clone at runtime, and without an ignore rule git reports them as
    # uncommitted changes — the update UI then shows a scary "local history
    # diverged" row on every install and nudges users toward force-updates
    # (observed live 2026-07-30). Ignore everything but the shipped scaffold.
    for rel in ("tesseract/voice/models/piper", "tesseract/voice/models/kokoro"):
        d = out_root / rel
        if d.is_dir():
            _write_state_dir_gitignore(d)

    # Last, so it overwrites the dev `.gitignore` copied in with the tracked
    # files. Must come after every generator above, since those decide what
    # the tree contains and this decides what survives publication.
    _write_root_gitignore(out_root)

    for rel in EMPTY_DIRS:
        d = out_root / rel
        if d.exists():
            shutil.rmtree(d, onexc=_force_remove)
        d.mkdir(parents=True)
        (d / ".gitkeep").write_text("", encoding="utf-8")
        _write_state_dir_gitignore(d)

    _write_seal_notices(src_root, out_root)


def _write_seal_notices(src_root: Path, out_root: Path) -> None:
    """Put the seal where a coding agent will actually read it.

    `SEALED.md` is prose nothing loads on its own. Claude Code auto-loads
    `CLAUDE.md` and Codex auto-loads `AGENTS.md` from the directory they start
    in — so a CLI launched inside the installed tree sees the rule before its
    first edit, without anyone having to tell it.

    Both filenames are excluded from the copied tree on purpose (the dev
    versions document the security architecture — see `_production_manifest.
    EXCLUDE_PATHS`), so these are generated, and deliberately carry no
    enforcement detail: the rule is the point, the mechanism is not.
    """
    sealed = (src_root / "tesseract" / "SEALED.md").read_text(encoding="utf-8")
    (out_root / "SEALED.md").write_text(sealed, encoding="utf-8")

    for name in ("CLAUDE.md", "AGENTS.md"):
        (out_root / name).write_text(
            f"# {name.split('.')[0].title()} instructions for this directory\n\n"
            "**This is a sealed application tree. Do not edit any file in it.**\n\n"
            "Read `SEALED.md` in this directory before doing anything else. The\n"
            "short version: this checkout is replaced wholesale by every update,\n"
            "so an edit made here is destroyed silently and reaches nobody. Read\n"
            "anything you like; write nothing.\n\n"
            "Write to the `home` directory beside this one instead: its\n"
            "`tars-workshop` folder for scratch work and drafts, its\n"
            "`downloads` folder for files you fetch.\n\n"
            "If the task genuinely requires changing this application, that work\n"
            "belongs in its development repository, not in the installed copy.\n"
            "Say so and stop rather than approximating the fix here.\n",
            encoding="utf-8",
        )


def main() -> None:
    ap = argparse.ArgumentParser(prog="python -m tesseract.scripts.build_production_tree")
    ap.add_argument("src_root", type=Path)
    ap.add_argument("out_root", type=Path)
    args = ap.parse_args()
    build(args.src_root, args.out_root)

    # CL-M7: fail the build itself on a PII/secret hit, not just at test time —
    # the shipped tree carries `scripts/audit_release_tree.py` as its own
    # standalone guard (tesseract/tests never ships), so run it here too.
    offenders = audit_release_tree.scan(args.out_root)
    if offenders:
        raise RuntimeError(
            "build_production_tree: release-audit found PII/secret pattern(s):\n"
            + "\n".join(offenders)
        )
    print(f"production tree written to {args.out_root}")


if __name__ == "__main__":
    main()
