"""KB tree scaffolding — ``vault/knowledge-base/{providers,cli-controls,ecosystem,roles}``.

Idempotent. Boot calls :func:`ensure_kb_tree` which creates missing
directories and seeds empty ``_refresh-log.jsonl`` files. The INDEX.md
is regenerated by :func:`render_index` each refresh.
"""

from __future__ import annotations

import os
from pathlib import Path

from tesseract.paths import TESSERACT_HOME

# Locked tree from `_shared/knowledge-base-layout.md`. Subdirs each get
# their own `_refresh-log.jsonl` and a `.last-refresh/` snapshot folder
# so the three-way merge has a known ancestor.
KB_SUBDIRS: tuple[str, ...] = (
    "providers",
    "cli-controls",
    "ecosystem",
    "roles",
)


def kb_root() -> Path:
    """Resolve ``<TESSERACT_HOME>/vault/knowledge-base/`` at call time so
    test fixtures setting ``TESSERACT_HOME`` after import reach the
    writers. Same pattern as ``workspace_changes.workspace_events_dir``.
    """
    override = os.environ.get("TESSERACT_HOME")
    home = Path(override).resolve() if override else TESSERACT_HOME
    return home / "vault" / "knowledge-base"


def ensure_kb_tree(root: Path | None = None) -> Path:
    """Create the KB tree if missing. Returns the root path.

    Idempotent — re-running on an existing tree is a no-op. Empty
    refresh logs are seeded only when missing so existing history isn't
    truncated.
    """
    base = root if root is not None else kb_root()
    base.mkdir(parents=True, exist_ok=True)
    for sub in KB_SUBDIRS:
        sd = base / sub
        sd.mkdir(parents=True, exist_ok=True)
        snap_dir = sd / ".last-refresh"
        snap_dir.mkdir(parents=True, exist_ok=True)
        # roles/ holds the auto-generated SUMMARY.md only; no scrape
        # source, no refresh log row of its own.
        if sub == "roles":
            continue
        log = sd / "_refresh-log.jsonl"
        if not log.exists():
            log.touch()
    index = base / "INDEX.md"
    if not index.exists():
        index.write_text(render_index(base), encoding="utf-8")
    return base


def render_index(base: Path) -> str:
    """Generate ``INDEX.md`` listing every KB markdown file."""
    lines: list[str] = [
        "# Knowledge base — index",
        "",
        "Auto-generated. Operator-local truth for providers / CLIs / ecosystem.",
        "",
    ]
    for sub in KB_SUBDIRS:
        sd = base / sub
        if not sd.exists():
            continue
        files = sorted(
            p
            for p in sd.glob("*.md")
            if not p.name.startswith("_") and not p.name.startswith(".")
        )
        if not files:
            continue
        lines.append(f"## {sub}")
        lines.append("")
        for f in files:
            lines.append(f"- [{f.stem}]({sub}/{f.name})")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def regenerate_index(base: Path | None = None) -> Path:
    """Overwrite ``INDEX.md`` with the current tree state."""
    root = base if base is not None else kb_root()
    root.mkdir(parents=True, exist_ok=True)
    target = root / "INDEX.md"
    target.write_text(render_index(root), encoding="utf-8")
    return target
