// The Guide is markdown first and a website second. Every page here also has
// to read correctly on GitHub, so the site is built around the existing tree
// rather than the tree being reshaped to suit the site: the pages stay where
// they are, the diagrams stay beside them, and the relative image paths that
// GitHub follows are the same ones Astro resolves at build.
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  site: 'https://tesseract.metaengineershub.com',
  integrations: [
    starlight({
      title: 'TESSERACT',
      description:
        'An assistant that runs on your machine, remembers you across sessions, ' +
        'and asks before it writes to a file or runs a command.',
      // Single-theme by commitment: the diagrams carry a fixed dark ground and
      // would read as broken on a light page.
      customCss: ['./src/styles/tesseract.css'],
      components: {
        // Single-theme by necessity; see the component for why.
        ThemeSelect: './src/components/ThemeSelect.astro',
      },
      social: [],
      pagination: true,
      // Mirrors SUMMARY.md. Kept explicit rather than autogenerated so the
      // reading order is a decision someone made, not alphabetical accident.
      sidebar: [
        {
          label: 'Start here',
          items: [
            { slug: 'start/what-it-is' },
            { slug: 'start/install' },
            { slug: 'start/first-hour' },
          ],
        },
        {
          label: 'How it works',
          items: [
            { slug: 'anatomy/system-context' },
            { slug: 'anatomy/agent-loop' },
            { slug: 'anatomy/voice' },
            { slug: 'anatomy/memory' },
            { slug: 'anatomy/autonomy' },
            { slug: 'anatomy/delegation' },
          ],
        },
        {
          label: 'Mechanisms',
          items: [
            { slug: 'mechanisms/permissions' },
            { slug: 'mechanisms/memory-and-vault' },
            { slug: 'mechanisms/prompts' },
            { slug: 'mechanisms/workspace' },
          ],
        },
        {
          label: 'Reference',
          badge: { text: 'generated', variant: 'note' },
          items: [
            { slug: 'reference/permissions' },
            { slug: 'reference/tools' },
            { slug: 'reference/models-and-roles' },
            { slug: 'reference/config' },
            { slug: 'reference/costs' },
          ],
        },
      ],
    }),
  ],
});
